name: Playwright browser test for corpus decoder

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: 'Test pages'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          python3 -m venv ~/venv
          ~/venv/bin/pip --disable-pip-version-check --no-input --no-cache-dir install --progress-bar off --prefer-binary '.[browser-tests]'
          source ~/venv/bin/activate
          python -m playwright install

      - name: Install Playwright system dependencies
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo rm -f /var/lib/man-db/auto-update
          source ~/venv/bin/activate
          playwright install-deps

      - name: Run Playwright browser test
        run: |
          source ~/venv/bin/activate
          pytest tests/browser/test_corpus_decoder.py
